source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '4.0.0'

gem 'bootstrap-sass'
gem 'coffee-rails', '~> 4.0.0'
gem 'flickraw'
gem 'haml'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'kaminari'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'sidekiq'
gem 'simple_form'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'erb2haml'
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'pry-debugger'
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'steak'
end
