common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 25
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *common
  database: searchflickr_development

test:
  <<: *common
  database: searchflickr_test

staging:
  <<: *common
  database: searchflickr_staging

production:
  <<: *common
  database: searchflickr_production
